export const MetaProjectTitle = "<BRAND>"; // Project title
export const MetaVersion = "v0.9.0"; // Version
export const MetaProjectSubtitle = "Data Design Language"; // Project subtitle
export const MetaLastUpdated = 1986; // Last updated
export const MetaAuthors = "Moritz Stefaner / Truth & Beauty with Christian Laesser, Alice Thudt, Flavio Gortana"; // Authors
export const EffectDepthCard = {"x":1,"y":1,"blur":3,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthHover = {"x":3,"y":3,"blur":6,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthModal = {"color":"#00000033","type":"dropShadow","x":0,"y":7,"blur":10,"spread":0};
export const EffectDepthUi = {"x":1,"y":1,"blur":2,"spread":0,"color":"#00000033","type":"dropShadow"};
export const SizeBreakpointXs = 480;
export const SizeBreakpointSm = 640;
export const SizeBreakpointMd = 960;
export const SizeBreakpointLg = 1200;
export const SizeBreakpointXl = 1440;
export const SizeMaxContentWidth = 1440;
export const SizeMinContentWidth = 320;
export const SizeBorderRadiusBase = 2;
export const SizeBorderRadiusBigger = 5;
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 2; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 3; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 4; // The largest border size. Used for the top chart container line.