export const SizeParameterFontSizeScaleFactor = 1.2;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeParameterFontSizeBase = 14;
export const SizeParameterSpaceScaleFactor = 1.25;
export const SizeParameterSpaceScaleFactorBelowOne = 1.25;
export const SizeParameterSpaceBase = 17.5;
export const SizeChartWidth = 480;
export const SizeViewportLimit = 320;
export const SizeMetaLabel = "Small";
export const SizeFontSizeXs = 11.57;
export const SizeFontSizeS = 12.727;
export const SizeFontSizeM = 14;
export const SizeFontSizeL = 16.8;
export const SizeFontSizeXl = 20.16;
export const SizeFontSizeXxl = 24.192;
export const SizeSpaceXxxxs = 5.734;
export const SizeSpaceXxxs = 7.168;
export const SizeSpaceXxs = 8.96;
export const SizeSpaceXs = 11.2;
export const SizeSpaceS = 14;
export const SizeSpaceM = 17.5;
export const SizeSpaceL = 21.875;
export const SizeSpaceXl = 27.344;
export const SizeSpaceXxl = 34.18;
export const SizeSpaceXxxl = 42.725;
export const SizeSpaceXxxxl = 53.406;
export const SizeSpaceXxxxxl = 66.757;
export const TypographyFontFamilyBase = "Inter";
export const TypographyFontFamilyHeading = "Inter";
export const TypographyFontFamilyMono = "Fira Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "145%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightBold = 700;
export const TypographyFontWeightSemiBold = 600;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const TypographyStyleBase = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"160%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // The default text style.
export const TypographyStyleHuge = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":24.192,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for summary statistics, large numbers, etc.
export const TypographyStyleTitle = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":20.16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for the title of a chart.
export const TypographyStyleMajorPrimary = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"145%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for legend main labels, as well as individual value annotations.
export const TypographyStyleMajorSecondary = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"145%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for secondary legend labels, description, and the chart subtitle.
export const TypographyStyleMinorPrimary = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":12.727,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for smaller annotations in charts.
export const TypographyStyleMinorSecondary = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"115%","fontSize":12.727,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for tick labels, secondary annotations, footer text.