export const SizeParameterFontSizeScaleFactor = 1.33;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeParameterFontSizeBase = 16;
export const SizeParameterSpaceScaleFactor = 1.5;
export const SizeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeParameterSpaceBase = 24;
export const SizeChartWidth = 1080;
export const SizeViewportLimit = 1440;
export const SizeMetaLabel = "Large";
export const SizeFontSizeXs = 12;
export const SizeFontSizeS = 15;
export const SizeFontSizeM = 16;
export const SizeFontSizeL = 21;
export const SizeFontSizeXl = 28;
export const SizeFontSizeXxl = 38;
export const SizeSpaceXxxxs = 3.161;
export const SizeSpaceXxxs = 4.741;
export const SizeSpaceXxs = 7.111;
export const SizeSpaceXs = 10.667;
export const SizeSpaceS = 16;
export const SizeSpaceM = 24;
export const SizeSpaceL = 36;
export const SizeSpaceXl = 54;
export const SizeSpaceXxl = 81;
export const SizeSpaceXxxl = 121.5;
export const SizeSpaceXxxxl = 182.25;
export const SizeSpaceXxxxxl = 273.375;
export const TypographyFontFamilyBase = "Inter";
export const TypographyFontFamilyHeading = "Inter";
export const TypographyFontFamilyMono = "Fira Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "145%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightBold = 700;
export const TypographyFontWeightSemiBold = 600;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const TypographyStyleBase = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"160%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // The default text style.
export const TypographyStyleHuge = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":38,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for summary statistics, large numbers, etc.
export const TypographyStyleTitle = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":28,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for the title of a chart.
export const TypographyStyleMajorPrimary = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"145%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for legend main labels, as well as individual value annotations.
export const TypographyStyleMajorSecondary = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"145%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for secondary legend labels, description, and the chart subtitle.
export const TypographyStyleMinorPrimary = {"fontFamily":"Inter","fontWeight":700,"lineHeight":"115%","fontSize":15,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for smaller annotations in charts.
export const TypographyStyleMinorSecondary = {"fontFamily":"Inter","fontWeight":400,"lineHeight":"115%","fontSize":15,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for tick labels, secondary annotations, footer text.