export const MetaProjectTitle = "<BRAND>"; // Project title
export const MetaVersion = "v0.9.0"; // Version
export const MetaProjectSubtitle = "Data Design Language"; // Project subtitle
export const MetaLastUpdated = 1986; // Last updated
export const MetaAuthors = "Moritz Stefaner / Truth & Beauty with Christian Laesser, Alice Thudt, Flavio Gortana"; // Authors
export const TypographyFontFamilyBase = "Inter";
export const TypographyFontFamilyHeading = "Inter";
export const TypographyFontFamilyMono = "Fira Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "145%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightBold = 700;
export const TypographyFontWeightSemiBold = 600;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const EffectDepthCard = {"x":1,"y":1,"blur":3,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthHover = {"x":3,"y":3,"blur":6,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthModal = {"color":"#00000033","type":"dropShadow","x":0,"y":7,"blur":10,"spread":0};
export const EffectDepthUi = {"x":1,"y":1,"blur":2,"spread":0,"color":"#00000033","type":"dropShadow"};
export const SizeBreakpointXs = 480;
export const SizeBreakpointSm = 640;
export const SizeBreakpointMd = 960;
export const SizeBreakpointLg = 1200;
export const SizeBreakpointXl = 1440;
export const SizeMaxContentWidth = 1440;
export const SizeMinContentWidth = 320;
export const SizeBorderRadiusBase = 2;
export const SizeBorderRadiusBigger = 5;
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 2; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 3; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 4; // The largest border size. Used for the top chart container line.
export const SizeBorderWidthDoubleS = 1; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleM = 2; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleL = 4; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXl = 6; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXxl = 8; // Double size of respective border token, for e.g. line background strokes.
export const SizeLargeParameterFontSizeScaleFactor = 1.33;
export const SizeLargeParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeLargeParameterFontSizeBase = 16;
export const SizeLargeParameterSpaceScaleFactor = 1.5;
export const SizeLargeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeLargeParameterSpaceBase = 24;
export const SizeLargeChartWidth = 1080;
export const SizeLargeViewportLimit = 1440;
export const SizeLargeMetaLabel = "Large";
export const SizeLargeConfigLargeFontSizeScaleFactor = 1.33;
export const SizeLargeConfigLargeFontSizeScaleFactorBelowOne = 1.1;
export const SizeLargeConfigLargeFontSizeBase = 16;
export const SizeLargeConfigLargeSpaceScaleFactor = 1.5;
export const SizeLargeConfigLargeSpaceScaleFactorBelowOne = 1.5;
export const SizeLargeConfigLargeSpaceBase = 24;
export const SizeLargeConfigSmallFontSizeScaleFactor = 1.2;
export const SizeLargeConfigSmallFontSizeScaleFactorBelowOne = 1.1;
export const SizeLargeConfigSmallFontSizeBase = 14;
export const SizeLargeConfigSmallSpaceScaleFactor = 1.25;
export const SizeLargeConfigSmallSpaceScaleFactorBelowOne = 1.25;
export const SizeLargeConfigSmallSpaceBase = 17.5;
export const SizeLargeFontSizeXs = 13.223;
export const SizeLargeFontSizeS = 14.545;
export const SizeLargeFontSizeM = 16;
export const SizeLargeFontSizeL = 21.28;
export const SizeLargeFontSizeXl = 28.302;
export const SizeLargeFontSizeXxl = 37.642;
export const SizeLargeSpaceXxxxs = 3.161;
export const SizeLargeSpaceXxxs = 4.741;
export const SizeLargeSpaceXxs = 7.111;
export const SizeLargeSpaceXs = 10.667;
export const SizeLargeSpaceS = 16;
export const SizeLargeSpaceM = 24;
export const SizeLargeSpaceL = 36;
export const SizeLargeSpaceXl = 54;
export const SizeLargeSpaceXxl = 81;
export const SizeLargeSpaceXxxl = 121.5;
export const SizeLargeSpaceXxxxl = 182.25;
export const SizeLargeSpaceXxxxxl = 273.375;
export const SizeSmallParameterFontSizeScaleFactor = 1.2;
export const SizeSmallParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeSmallParameterFontSizeBase = 14;
export const SizeSmallParameterSpaceScaleFactor = 1.25;
export const SizeSmallParameterSpaceScaleFactorBelowOne = 1.25;
export const SizeSmallParameterSpaceBase = 17.5;
export const SizeSmallChartWidth = 480;
export const SizeSmallViewportLimit = 480;
export const SizeSmallMetaLabel = "Small";
export const SizeSmallConfigLargeFontSizeScaleFactor = 1.33;
export const SizeSmallConfigLargeFontSizeScaleFactorBelowOne = 1.1;
export const SizeSmallConfigLargeFontSizeBase = 16;
export const SizeSmallConfigLargeSpaceScaleFactor = 1.5;
export const SizeSmallConfigLargeSpaceScaleFactorBelowOne = 1.5;
export const SizeSmallConfigLargeSpaceBase = 24;
export const SizeSmallConfigSmallFontSizeScaleFactor = 1.2;
export const SizeSmallConfigSmallFontSizeScaleFactorBelowOne = 1.1;
export const SizeSmallConfigSmallFontSizeBase = 14;
export const SizeSmallConfigSmallSpaceScaleFactor = 1.25;
export const SizeSmallConfigSmallSpaceScaleFactorBelowOne = 1.25;
export const SizeSmallConfigSmallSpaceBase = 17.5;
export const SizeSmallFontSizeXs = 11.57;
export const SizeSmallFontSizeS = 12.727;
export const SizeSmallFontSizeM = 14;
export const SizeSmallFontSizeL = 16.8;
export const SizeSmallFontSizeXl = 20.16;
export const SizeSmallFontSizeXxl = 24.192;
export const SizeSmallSpaceXxxxs = 5.734;
export const SizeSmallSpaceXxxs = 7.168;
export const SizeSmallSpaceXxs = 8.96;
export const SizeSmallSpaceXs = 11.2;
export const SizeSmallSpaceS = 14;
export const SizeSmallSpaceM = 17.5;
export const SizeSmallSpaceL = 21.875;
export const SizeSmallSpaceXl = 27.344;
export const SizeSmallSpaceXxl = 34.18;
export const SizeSmallSpaceXxxl = 42.725;
export const SizeSmallSpaceXxxxl = 53.406;
export const SizeSmallSpaceXxxxxl = 66.757;
export const ColorDarkMetaLabel = "#000000";
export const ColorDarkBackgroundBase = "#111111";
export const ColorDarkBackgroundWeaker = "#333333"; // slightly shaded background
export const ColorDarkBackgroundWeakest = "#666666";
export const ColorDarkForegroundBase = "#eaeaea";
export const ColorDarkForegroundWeaker = "#abafb0";
export const ColorDarkForegroundWeakest = "#717576";
export const ColorDarkTextWeaker = "#abafb0";
export const ColorDarkTextBase = "#f8f8f8";
export const ColorDarkTextStronger = "#ffffff"; // Stronger text color for maximum background contrast.
export const ColorDarkThemeBase = "#44a8c3";
export const ColorDarkThemeWeaker = "#256f81";
export const ColorDarkThemeStronger = "#83c3d4";
export const ColorDarkFunctionalAccent = "#ffcb01";
export const ColorDarkFunctionalFocus = "#ffcb01";
export const ColorDarkFunctionalNotAvailable = "#cccccc";
export const ColorDarkFunctionalFilteredOut = "#474b69";
export const ColorDarkCategoryStronger0 = "#83bad9";
export const ColorDarkCategoryStronger1 = "#b386c8";
export const ColorDarkCategoryStronger2 = "#e38c7c";
export const ColorDarkCategoryStronger3 = "#f8c975";
export const ColorDarkCategoryStronger4 = "#83c0a4";
export const ColorDarkCategoryStronger5 = "#ced56d";
export const ColorDarkCategoryStronger99 = "#c0c8d2";
export const ColorDarkCategoryBase0 = "#22699a";
export const ColorDarkCategoryBase1 = "#825497";
export const ColorDarkCategoryBase2 = "#c85543";
export const ColorDarkCategoryBase3 = "#dc9d38";
export const ColorDarkCategoryBase4 = "#458a69";
export const ColorDarkCategoryBase5 = "#7e8518";
export const ColorDarkCategoryBase99 = "#9ea9b5";
export const ColorDarkCategoryWeaker0 = "#124874";
export const ColorDarkCategoryWeaker1 = "#613f70";
export const ColorDarkCategoryWeaker2 = "#993d31";
export const ColorDarkCategoryWeaker3 = "#a07730";
export const ColorDarkCategoryWeaker4 = "#366d53";
export const ColorDarkCategoryWeaker5 = "#575b20";
export const ColorDarkCategoryWeaker99 = "#6b7581";
export const ColorDarkComplementaryBase = "#cc4233"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDarkComplementaryWeaker = "#832521"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDarkComplementaryStronger = "#da5c4b"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDarkDivergingPositive1 = "#256f81";
export const ColorDarkDivergingPositive2 = "#66b5cb";
export const ColorDarkDivergingNeutral = "#2c343e";
export const ColorDarkDivergingNegative1 = "#832521";
export const ColorDarkDivergingNegative2 = "#da5c4b";
export const ColorDarkSequential0 = "#175462";
export const ColorDarkSequential1 = "#348ba1";
export const ColorDarkSequential2 = "#66b5cb";
export const ColorDarkSequential3 = "#9ed0dd";
export const ColorDarkSequentialPositive0 = "#175462";
export const ColorDarkSequentialPositive1 = "#348ba1";
export const ColorDarkSequentialPositive2 = "#66b5cb";
export const ColorDarkSequentialPositive3 = "#9ed0dd";
export const ColorDarkSequentialNegative0 = "#601817";
export const ColorDarkSequentialNegative1 = "#a7332a";
export const ColorDarkSequentialNegative2 = "#da5c4b";
export const ColorDarkSequentialNegative3 = "#f38c7c";
export const ColorLightMetaLabel = "#000000";
export const ColorLightBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorLightBackgroundWeaker = "#f1f2f3"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorLightBackgroundWeakest = "#e0e2e4"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorLightForegroundBase = "#191919"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorLightForegroundWeaker = "#6b7581"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorLightForegroundWeakest = "#c0c8d2"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorLightTextBase = "#191919"; // Default text color for strong background contrast.
export const ColorLightTextWeaker = "#6b7581"; // Text color with weaker background contrast.
export const ColorLightThemeWeaker = "#79abbc"; // Weaker version of theme color
export const ColorLightThemeBase = "#377796"; // Main theme color, usually the brand color.
export const ColorLightThemeStronger = "#0e3e63"; // Stronger version of theme color
export const ColorLightFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorLightFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorLightFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorLightFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorLightCategoryBase0 = "#297cb5";
export const ColorLightCategoryBase1 = "#905ea7";
export const ColorLightCategoryBase2 = "#de5f4a";
export const ColorLightCategoryBase3 = "#ffa81b";
export const ColorLightCategoryBase4 = "#51a27c";
export const ColorLightCategoryBase5 = "#9da61d";
export const ColorLightCategoryBase99 = "#9ea9b5";
export const ColorLightCategoryWeaker0 = "#83bad9";
export const ColorLightCategoryWeaker1 = "#b386c8";
export const ColorLightCategoryWeaker2 = "#e38c7c";
export const ColorLightCategoryWeaker3 = "#f8c975";
export const ColorLightCategoryWeaker4 = "#83c0a4";
export const ColorLightCategoryWeaker5 = "#ced56d";
export const ColorLightCategoryWeaker99 = "#c0c8d2";
export const ColorLightCategoryStronger0 = "#0161a3";
export const ColorLightCategoryStronger1 = "#492658";
export const ColorLightCategoryStronger2 = "#a72817";
export const ColorLightCategoryStronger3 = "#b26d00";
export const ColorLightCategoryStronger4 = "#0b5932";
export const ColorLightCategoryStronger5 = "#565d00";
export const ColorLightCategoryStronger99 = "#6b7581";
export const ColorLightDivergingNegative1 = "#e98676"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorLightDivergingNegative2 = "#a12917"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorLightDivergingNeutral = "#e0e2e4"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorLightDivergingPositive1 = "#0e3e63"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorLightDivergingPositive2 = "#79abbc"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorLightComplementaryWeaker = "#e98676"; // Weaker version of complementary color.
export const ColorLightComplementaryBase = "#dc6454"; // Main complementary color.
export const ColorLightComplementaryStronger = "#a12917"; // Stronger version of complementary color.
export const ColorLightSequential0 = "#c3d6dc";
export const ColorLightSequential1 = "#79abbc";
export const ColorLightSequential2 = "#377796";
export const ColorLightSequential3 = "#0e3e63";
export const ColorLightSequentialPositive0 = "#c3d6dc"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorLightSequentialPositive1 = "#79abbc"; // Second step in the base (theme) sequential color scale.
export const ColorLightSequentialPositive2 = "#377796"; // Thirs step in the base (theme) sequential color scale.
export const ColorLightSequentialPositive3 = "#0e3e63"; // Third and final step in the base (theme) sequential color scale.
export const ColorLightSequentialNegative0 = "#fbc8bf";
export const ColorLightSequentialNegative1 = "#e98676";
export const ColorLightSequentialNegative2 = "#c9513f";
export const ColorLightSequentialNegative3 = "#a12917";