export const ColorGrey100 = "#191919";
export const ColorGrey300 = "#3d4246";
export const ColorGrey400 = "#6b7581";
export const ColorGrey500 = "#9ea9b5";
export const ColorGrey600 = "#c0c8d2";
export const ColorGrey750 = "#e0e2e4";
export const ColorGrey800 = "#f1f2f3";
export const ColorGrey900 = "#ffffff";
export const ColorGrey000 = "#000000";
export const ColorTeal100 = "#002348";
export const ColorTeal200 = "#0e3e63";
export const ColorTeal300 = "#215a7d";
export const ColorTeal400 = "#377796";
export const ColorTeal500 = "#5196ae";
export const ColorTeal600 = "#79abbc";
export const ColorTeal700 = "#9fc1cc";
export const ColorTeal800 = "#c3d6dc";
export const ColorTeal900 = "#e8eced";
export const ColorRed100 = "#8d1000";
export const ColorRed200 = "#a12917";
export const ColorRed300 = "#b53d2b";
export const ColorRed400 = "#c9513f";
export const ColorRed500 = "#dc6454";
export const ColorRed600 = "#e98676";
export const ColorRed700 = "#f3a79a";
export const ColorRed800 = "#fbc8bf";
export const ColorRed900 = "#ffe9e5";
export const ColorRedDark100 = "#400c0a";
export const ColorRedDark200 = "#601817";
export const ColorRedDark300 = "#832521";
export const ColorRedDark400 = "#a7332a";
export const ColorRedDark500 = "#cc4233";
export const ColorRedDark600 = "#da5c4b";
export const ColorRedDark700 = "#e77463";
export const ColorRedDark800 = "#f38c7c";
export const ColorRedDark900 = "#fea496";
export const ColorTealDark100 = "#093a45";
export const ColorTealDark200 = "#175462";
export const ColorTealDark300 = "#256f81";
export const ColorTealDark400 = "#348ba1";
export const ColorTealDark500 = "#44a8c3";
export const ColorTealDark600 = "#66b5cb";
export const ColorTealDark700 = "#83c3d4";
export const ColorTealDark800 = "#9ed0dd";
export const ColorTealDark900 = "#b8dee7";
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f1f2f3"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#e0e2e4"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#191919"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeaker = "#6b7581"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeakest = "#c0c8d2"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorTextBase = "#191919"; // Default text color for strong background contrast.
export const ColorTextWeaker = "#6b7581"; // Text color with weaker background contrast.
export const ColorThemeWeaker = "#79abbc"; // Weaker version of theme color
export const ColorThemeBase = "#377796"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#0e3e63"; // Stronger version of theme color
export const ColorFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorCategoryBase0 = "#297cb5";
export const ColorCategoryBase1 = "#905ea7";
export const ColorCategoryBase2 = "#de5f4a";
export const ColorCategoryBase3 = "#ffa81b";
export const ColorCategoryBase4 = "#51a27c";
export const ColorCategoryBase5 = "#9da61d";
export const ColorCategoryBase99 = "#9ea9b5";
export const ColorCategoryWeaker0 = "#83bad9";
export const ColorCategoryWeaker1 = "#b386c8";
export const ColorCategoryWeaker2 = "#e38c7c";
export const ColorCategoryWeaker3 = "#f8c975";
export const ColorCategoryWeaker4 = "#83c0a4";
export const ColorCategoryWeaker5 = "#ced56d";
export const ColorCategoryWeaker99 = "#c0c8d2";
export const ColorCategoryStronger0 = "#0161a3";
export const ColorCategoryStronger1 = "#492658";
export const ColorCategoryStronger2 = "#a72817";
export const ColorCategoryStronger3 = "#b26d00";
export const ColorCategoryStronger4 = "#0b5932";
export const ColorCategoryStronger5 = "#565d00";
export const ColorCategoryStronger99 = "#6b7581";
export const ColorDivergingNegative1 = "#e98676"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#a12917"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#e0e2e4"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#0e3e63"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorDivergingPositive2 = "#79abbc"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorComplementaryWeaker = "#e98676"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#dc6454"; // Main complementary color.
export const ColorComplementaryStronger = "#a12917"; // Stronger version of complementary color.
export const ColorSequential0 = "#c3d6dc";
export const ColorSequential1 = "#79abbc";
export const ColorSequential2 = "#377796";
export const ColorSequential3 = "#0e3e63";
export const ColorSequentialPositive0 = "#c3d6dc"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#79abbc"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#377796"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#0e3e63"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#fbc8bf";
export const ColorSequentialNegative1 = "#e98676";
export const ColorSequentialNegative2 = "#c9513f";
export const ColorSequentialNegative3 = "#a12917";