export const MetaProjectTitle = "<BRAND>"; // Project title
export const MetaVersion = "v0.9.0"; // Version
export const MetaProjectSubtitle = "Data Design Language"; // Project subtitle
export const MetaLastUpdated = 1986; // Last updated
export const MetaAuthors = "Moritz Stefaner / Truth & Beauty with Christian Laesser, Alice Thudt, Flavio Gortana"; // Authors
export const TypographyFontFamilyBase = "Inter";
export const TypographyFontFamilyHeading = "Inter";
export const TypographyFontFamilyMono = "Fira Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "145%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightBold = 700;
export const TypographyFontWeightSemiBold = 600;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const EffectDepthCard = {"x":1,"y":1,"blur":3,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthHover = {"x":3,"y":3,"blur":6,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectDepthModal = {"color":"#00000033","type":"dropShadow","x":0,"y":7,"blur":10,"spread":0};
export const EffectDepthUi = {"x":1,"y":1,"blur":2,"spread":0,"color":"#00000033","type":"dropShadow"};
export const SizeParameterFontSizeScaleFactor = 1.33;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeParameterFontSizeBase = 16;
export const SizeParameterSpaceScaleFactor = 1.5;
export const SizeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeParameterSpaceBase = 24;
export const SizeBreakpointXs = 480;
export const SizeBreakpointSm = 640;
export const SizeBreakpointMd = 960;
export const SizeBreakpointLg = 1200;
export const SizeBreakpointXl = 1440;
export const SizeMaxContentWidth = 1440;
export const SizeMinContentWidth = 320;
export const SizeChartWidth = 1080;
export const SizeFontSizeXs = 13.223;
export const SizeFontSizeS = 14.545;
export const SizeFontSizeM = 16;
export const SizeFontSizeL = 21.28;
export const SizeFontSizeXl = 28.302;
export const SizeFontSizeXxl = 37.642;
export const SizeSpaceXxxxs = 3.161;
export const SizeSpaceXxxs = 4.741;
export const SizeSpaceXxs = 7.111;
export const SizeSpaceXs = 10.667;
export const SizeSpaceS = 16;
export const SizeSpaceM = 24;
export const SizeSpaceL = 36;
export const SizeSpaceXl = 54;
export const SizeSpaceXxl = 81;
export const SizeSpaceXxxl = 121.5;
export const SizeSpaceXxxxl = 182.25;
export const SizeSpaceXxxxxl = 273.375;
export const SizeBorderRadiusBase = 2;
export const SizeBorderRadiusBigger = 5;
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 2; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 3; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 4; // The largest border size. Used for the top chart container line.
export const SizeBorderWidthDoubleS = 1; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleM = 2; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleL = 4; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXl = 6; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXxl = 8; // Double size of respective border token, for e.g. line background strokes.
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f1f2f3"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#e0e2e4"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#191919"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeaker = "#6b7581"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeakest = "#c0c8d2"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorTextBase = "#191919"; // Default text color for strong background contrast.
export const ColorTextWeaker = "#6b7581"; // Text color with weaker background contrast.
export const ColorThemeWeaker = "#79abbc"; // Weaker version of theme color
export const ColorThemeBase = "#377796"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#0e3e63"; // Stronger version of theme color
export const ColorFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorCategoryBase0 = "#297cb5";
export const ColorCategoryBase1 = "#905ea7";
export const ColorCategoryBase2 = "#de5f4a";
export const ColorCategoryBase3 = "#ffa81b";
export const ColorCategoryBase4 = "#51a27c";
export const ColorCategoryBase5 = "#9da61d";
export const ColorCategoryBase99 = "#9ea9b5";
export const ColorCategoryWeaker0 = "#83bad9";
export const ColorCategoryWeaker1 = "#b386c8";
export const ColorCategoryWeaker2 = "#e38c7c";
export const ColorCategoryWeaker3 = "#f8c975";
export const ColorCategoryWeaker4 = "#83c0a4";
export const ColorCategoryWeaker5 = "#ced56d";
export const ColorCategoryWeaker99 = "#c0c8d2";
export const ColorCategoryStronger0 = "#0161a3";
export const ColorCategoryStronger1 = "#492658";
export const ColorCategoryStronger2 = "#a72817";
export const ColorCategoryStronger3 = "#b26d00";
export const ColorCategoryStronger4 = "#0b5932";
export const ColorCategoryStronger5 = "#565d00";
export const ColorCategoryStronger99 = "#6b7581";
export const ColorDivergingNegative1 = "#e98676"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#a12917"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#e0e2e4"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#0e3e63"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorDivergingPositive2 = "#79abbc"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorComplementaryWeaker = "#e98676"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#dc6454"; // Main complementary color.
export const ColorComplementaryStronger = "#a12917"; // Stronger version of complementary color.
export const ColorSequential0 = "#c3d6dc";
export const ColorSequential1 = "#79abbc";
export const ColorSequential2 = "#377796";
export const ColorSequential3 = "#0e3e63";
export const ColorSequentialPositive0 = "#c3d6dc"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#79abbc"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#377796"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#0e3e63"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#fbc8bf";
export const ColorSequentialNegative1 = "#e98676";
export const ColorSequentialNegative2 = "#c9513f";
export const ColorSequentialNegative3 = "#a12917";