/**
 * Do not edit directly
 * Generated on Tue, 08 Nov 2022 12:54:19 GMT
 */

export const TypographyStylesBaseFontFamily = "Inter";
export const TypographyStylesBaseFontWeight = 400;
export const TypographyStylesBaseLineHeight = "160%";
export const TypographyStylesBaseFontSize = 16;
export const TypographyStylesBaseLetterSpacing = "0%";
export const TypographyStylesBaseParagraphSpacing = 8;
export const TypographyStylesBaseTextDecoration = "none";
export const TypographyStylesBaseTextCase = "none";
export const TypographyStylesHugeFontFamily = "Inter";
export const TypographyStylesHugeFontWeight = 700;
export const TypographyStylesHugeLineHeight = "115%";
export const TypographyStylesHugeFontSize = 37.642;
export const TypographyStylesHugeLetterSpacing = "0%";
export const TypographyStylesHugeParagraphSpacing = 8;
export const TypographyStylesHugeTextDecoration = "none";
export const TypographyStylesHugeTextCase = "none";
export const TypographyStylesTitleFontFamily = "Inter";
export const TypographyStylesTitleFontWeight = 700;
export const TypographyStylesTitleLineHeight = "115%";
export const TypographyStylesTitleFontSize = 28.302;
export const TypographyStylesTitleLetterSpacing = "0%";
export const TypographyStylesTitleParagraphSpacing = 8;
export const TypographyStylesTitleTextDecoration = "none";
export const TypographyStylesTitleTextCase = "none";
export const TypographyStylesMajorPrimaryFontFamily = "Inter";
export const TypographyStylesMajorPrimaryFontWeight = 700;
export const TypographyStylesMajorPrimaryLineHeight = "145%";
export const TypographyStylesMajorPrimaryFontSize = 16;
export const TypographyStylesMajorPrimaryLetterSpacing = "0%";
export const TypographyStylesMajorPrimaryParagraphSpacing = 8;
export const TypographyStylesMajorPrimaryTextDecoration = "none";
export const TypographyStylesMajorPrimaryTextCase = "none";
export const TypographyStylesMajorSecondaryFontFamily = "Inter";
export const TypographyStylesMajorSecondaryFontWeight = 400;
export const TypographyStylesMajorSecondaryLineHeight = "145%";
export const TypographyStylesMajorSecondaryFontSize = 16;
export const TypographyStylesMajorSecondaryLetterSpacing = "0%";
export const TypographyStylesMajorSecondaryParagraphSpacing = 8;
export const TypographyStylesMajorSecondaryTextDecoration = "none";
export const TypographyStylesMajorSecondaryTextCase = "none";
export const TypographyStylesMinorPrimaryFontFamily = "Inter";
export const TypographyStylesMinorPrimaryFontWeight = 700;
export const TypographyStylesMinorPrimaryLineHeight = "115%";
export const TypographyStylesMinorPrimaryFontSize = 14.545;
export const TypographyStylesMinorPrimaryLetterSpacing = "0%";
export const TypographyStylesMinorPrimaryParagraphSpacing = 8;
export const TypographyStylesMinorPrimaryTextDecoration = "none";
export const TypographyStylesMinorPrimaryTextCase = "none";
export const TypographyStylesMinorSecondaryFontFamily = "Inter";
export const TypographyStylesMinorSecondaryFontWeight = 400;
export const TypographyStylesMinorSecondaryLineHeight = "115%";
export const TypographyStylesMinorSecondaryFontSize = 14.545;
export const TypographyStylesMinorSecondaryLetterSpacing = "0%";
export const TypographyStylesMinorSecondaryParagraphSpacing = 8;
export const TypographyStylesMinorSecondaryTextDecoration = "none";
export const TypographyStylesMinorSecondaryTextCase = "none";
export const TypographyFontFamilyBase = "Inter";
export const TypographyFontFamilyHeading = "Inter";
export const TypographyFontFamilyMono = "IBM Plex Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "145%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightBold = 700;
export const TypographyFontWeightSemiBold = 600;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const MetaProjectTitle = "<BRAND>"; // Project title
export const MetaVersion = "v0.9.0"; // Version
export const MetaProjectSubtitle = "Data Design Language"; // Project subtitle
export const MetaLastUpdated = 1986; // Last updated
export const MetaAuthors = "Moritz Stefaner / Truth & Beauty with Christian Laesser, Alice Thudt, Flavio Gortana"; // Authors
export const ParameterSizeFontSizeScaleFactor = 1.33;
export const ParameterSizeFontSizeScaleFactorBelowOne = 1.1;
export const ParameterSizeFontSizeBase = 16;
export const ParameterSizeSpaceScaleFactor = 1.5;
export const ParameterSizeSpaceScaleFactorBelowOne = 1.5;
export const ParameterSizeSpaceBase = 24;
export const EffectDepthCardX = 1;
export const EffectDepthCardY = 1;
export const EffectDepthCardBlur = 3;
export const EffectDepthCardSpread = 0;
export const EffectDepthCardColor = "#00000033";
export const EffectDepthCardType = "dropShadow";
export const EffectDepthHoverX = 3;
export const EffectDepthHoverY = 3;
export const EffectDepthHoverBlur = 6;
export const EffectDepthHoverSpread = 0;
export const EffectDepthHoverColor = "#00000033";
export const EffectDepthHoverType = "dropShadow";
export const EffectDepthModalColor = "#00000033";
export const EffectDepthModalType = "dropShadow";
export const EffectDepthModalX = 0;
export const EffectDepthModalY = 7;
export const EffectDepthModalBlur = 10;
export const EffectDepthModalSpread = 0;
export const EffectDepthUiX = 1;
export const EffectDepthUiY = 1;
export const EffectDepthUiBlur = 2;
export const EffectDepthUiSpread = 0;
export const EffectDepthUiColor = "#00000033";
export const EffectDepthUiType = "dropShadow";
export const SizeBreakpointXs = "480rem";
export const SizeBreakpointSm = "640rem";
export const SizeBreakpointMd = "960rem";
export const SizeBreakpointLg = "1200rem";
export const SizeBreakpointXl = "1440rem";
export const SizeMaxContentWidth = "1440rem";
export const SizeMinContentWidth = "320rem";
export const SizeChartWidth = "1080rem";
export const SizeFontSizeXs = "13.223rem";
export const SizeFontSizeS = "14.545rem";
export const SizeFontSizeM = "16rem";
export const SizeFontSizeL = "21.28rem";
export const SizeFontSizeXl = "28.302rem";
export const SizeFontSizeXxl = "37.642rem";
export const SizeSpaceXxxxs = "3.161rem";
export const SizeSpaceXxxs = "4.741rem";
export const SizeSpaceXxs = "7.111rem";
export const SizeSpaceXs = "10.667rem";
export const SizeSpaceS = "16rem";
export const SizeSpaceM = "24rem";
export const SizeSpaceL = "36rem";
export const SizeSpaceXl = "54rem";
export const SizeSpaceXxl = "81rem";
export const SizeSpaceXxxl = "121.5rem";
export const SizeSpaceXxxxl = "182.25rem";
export const SizeSpaceXxxxxl = "273.375rem";
export const SizeBorderRadiusBase = "2rem";
export const SizeBorderRadiusBigger = "5rem";
export const SizeBorderWidthS = "0.5rem"; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = "1rem"; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = "2rem"; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = "3rem"; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = "4rem"; // The largest border size. Used for the top chart container line.
export const SizeBorderWidthDoubleS = "1rem"; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleM = "2rem"; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleL = "4rem"; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXl = "6rem"; // Double size of respective border token, for e.g. line background strokes.
export const SizeBorderWidthDoubleXxl = "8rem"; // Double size of respective border token, for e.g. line background strokes.
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f1f2f3"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#e0e2e4"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#191919"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeaker = "#6b7581"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeakest = "#c0c8d2"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorTextBase = "#191919"; // Default text color for strong background contrast.
export const ColorTextWeaker = "#6b7581"; // Text color with weaker background contrast.
export const ColorThemeWeaker = "#79abbc"; // Weaker version of theme color
export const ColorThemeBase = "#377796"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#0e3e63"; // Stronger version of theme color
export const ColorFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorCategoryBase0 = "#297cb5";
export const ColorCategoryBase1 = "#905ea7";
export const ColorCategoryBase2 = "#de5f4a";
export const ColorCategoryBase3 = "#ffa81b";
export const ColorCategoryBase4 = "#51a27c";
export const ColorCategoryBase5 = "#9da61d";
export const ColorCategoryBase99 = "#9ea9b5";
export const ColorCategoryWeaker0 = "#83bad9";
export const ColorCategoryWeaker1 = "#b386c8";
export const ColorCategoryWeaker2 = "#e38c7c";
export const ColorCategoryWeaker3 = "#f8c975";
export const ColorCategoryWeaker4 = "#83c0a4";
export const ColorCategoryWeaker5 = "#ced56d";
export const ColorCategoryWeaker99 = "#c0c8d2";
export const ColorCategoryStronger0 = "#0161a3";
export const ColorCategoryStronger1 = "#492658";
export const ColorCategoryStronger2 = "#a72817";
export const ColorCategoryStronger3 = "#b26d00";
export const ColorCategoryStronger4 = "#0b5932";
export const ColorCategoryStronger5 = "#565d00";
export const ColorCategoryStronger99 = "#6b7581";
export const ColorDivergingNegative1 = "#e98676"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#a12917"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#e0e2e4"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#0e3e63"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorDivergingPositive2 = "#79abbc"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorComplementaryWeaker = "#e98676"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#dc6454"; // Main complementary color.
export const ColorComplementaryStronger = "#a12917"; // Stronger version of complementary color.
export const ColorSequential0 = "#c3d6dc";
export const ColorSequential1 = "#79abbc";
export const ColorSequential2 = "#377796";
export const ColorSequential3 = "#0e3e63";
export const ColorSequentialPositive0 = "#c3d6dc"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#79abbc"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#377796"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#0e3e63"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#fbc8bf";
export const ColorSequentialNegative1 = "#e98676";
export const ColorSequentialNegative2 = "#c9513f";
export const ColorSequentialNegative3 = "#a12917";